### ISSUE TITLE
Users should not be able to give themselves karma

### ISSUE THREAD

**Issue by cnellis101** [tnorris/discord-karmabot#1]
Users should not be able to give themselves karma, it should have a snarky message telling you what an awful person you are for even trying.

Something like this maybe in `add_increment_handler` and `add_decrement_handler`
Don't know any ruby so this was my best guess.

```
unless thing(contains: @bot.message.author) do
  # Do amazing things!
end
```

**Comment by jmeichle** [comment]
:+1:

**Comment by tnorris** [comment]
Fixed!
